if [ -x /opt/homebrew/bin/brew ]; then
    PATH=$(/opt/homebrew/bin/brew --prefix):$PATH
    export PATH
fi

if which neofetch >/dev/null; then
    if [ ! -n "$TMUX" ] && [ -f "$HOME/.config/neofetch/config.conf" ]; then
        $(which neofetch)
    fi
fi
