export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

if [ -d /opt/homebrew/bin ]; then
    PATH=/opt/homebrew/bin:$PATH
    export PATH
fi

if [ -d /opt/homebrew/sbin ]; then
    PATH=/opt/homebrew/sbin:$PATH
    export PATH
fi

if which neofetch >/dev/null; then
    if [ ! -n "$TMUX" ] && [ -f "$HOME/.config/neofetch/config.conf" ]; then
        $(which neofetch)
    fi
fi
