#!/usr/bin/env zsh
export COLORTERM=truecolor
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# Check for updates
test -e $HOME/.dotfiles/update_online.sh && /bin/bash $HOME/.dotfiles/update_online.sh

# Load Antigen
test -e $(brew --prefix)/share/antigen/antigen.zsh && source $(brew --prefix)/share/antigen/antigen.zsh
test -e $HOME/.antigenrc && antigen init $HOME/.antigenrc
autoload -U compinit && compinit -u

setopt AUTOCD
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY
setopt NO_BEEP
setopt SHARE_HISTORY

# Source p10k files
test -e $HOME/.p10k.zsh && source $HOME/.p10k.zsh

# Cleanup
typeset -U PATH
export PATH
